/* DO NOT EDIT THIS FILE - it is machine generated */
#ifdef ACLASLOADER_EXPORTS
#define ACLASLOADER_API __declspec(dllexport)
#else
#define ACLASLOADER_API __declspec(dllimport)
#endif

#include "jni.h"
#import "AclasDriver.dll" no_namespace, raw_interfaces_only
/* Header for class com_onegolabs_wamanager_scales_aclas_AclasLoader */

#ifndef _Included_com_onegolabs_wamanager_scales_aclas_AclasLoader
#define _Included_com_onegolabs_wamanager_scales_aclas_AclasLoader
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_onegolabs_wamanager_scales_aclas_AclasLoader
	 * Method:    connectToScales
	 * Signature: (Ljava/lang/String;)Z
	 */
	JNIEXPORT jboolean JNICALL Java_com_onegolabs_wamanager_scales_aclas_AclasLoader_connectToScales
	(JNIEnv *, jobject, jstring);

	/*
	 * Class:     com_onegolabs_wamanager_scales_aclas_AclasLoader
	 * Method:    addMessage
	 * Signature: ()I
	 */
	JNIEXPORT jint JNICALL Java_com_onegolabs_wamanager_scales_aclas_AclasLoader_addMessage
	(JNIEnv *, jobject);

	/*
	 * Class:     com_onegolabs_wamanager_scales_aclas_AclasLoader
	 * Method:    setMessageLine
	 * Signature: (ILjava/lang/String;)Z
	 */
	JNIEXPORT jboolean JNICALL Java_com_onegolabs_wamanager_scales_aclas_AclasLoader_setMessageLine
	(JNIEnv *, jobject, jint, jstring);

	/*
	 * Class:     com_onegolabs_wamanager_scales_aclas_AclasLoader
	 * Method:    sendArticleToScales
	 * Signature: (IILjava/lang/String;DIIIII)I
	 */
	JNIEXPORT jint JNICALL Java_com_onegolabs_wamanager_scales_aclas_AclasLoader_sendArticleToScales
	(JNIEnv *, jobject, jint, jint, jstring, jdouble, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     com_onegolabs_wamanager_scales_aclas_AclasLoader
	 * Method:    flushBuffers
	 * Signature: ()Z
	 */
	JNIEXPORT jboolean JNICALL Java_com_onegolabs_wamanager_scales_aclas_AclasLoader_flushBuffers
	(JNIEnv *, jobject);

	/*
	 * Class:     com_onegolabs_wamanager_scales_aclas_AclasLoader
	 * Method:    clearAllPLUAndMessages
	 * Signature: ()Z
	 */
	JNIEXPORT jboolean JNICALL Java_com_onegolabs_wamanager_scales_aclas_AclasLoader_clearAllPLUAndMessages
	(JNIEnv *, jobject);

	/*
	 * Class:     com_onegolabs_wamanager_scales_aclas_AclasLoader
	 * Method:    disconnectFromScales
	 * Signature: ()Z
	 */
	JNIEXPORT jboolean JNICALL Java_com_onegolabs_wamanager_scales_aclas_AclasLoader_disconnectFromScales
	(JNIEnv *, jobject);

#define JSTR2BSTR(env, bs, js)												 \
	_bstr_t bs;																 \
	if (TRUE) {																 \
		jboolean isCopy = 1;												 \
		bs = (const wchar_t*)env->GetStringChars(js, &isCopy);				 \
		if (isCopy) {														 \
			/* TODO: free jstring (how?) */									 \
		}																	 \
	}

#define BSTR2JSTR(env, bs)													 \
	env->NewString((const jchar*)(wchar_t*)bs, bs.length())

#ifdef __cplusplus
}
#endif
#endif
